name: Pull Request Assigner

on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    branches:
    - main
    - adi-main*
    - collab-*
    - v*-branch
  issues:
    types:
    - labeled

jobs:
  assignment:
    name: Pull Request Assignment
    if: github.event.pull_request.draft == false
    runs-on: ses-edi-build-lu-x64-10

    steps:
    - name: Remove Possible Existing Access Token
      continue-on-error: true
      run: |
        # Token is generated at the run time and at the end of process it is expires,
        # storing it in global config causes duplication line in config file
        # so that possible existing one shall be deleted before generating new one
        # otherwiser autantication will be failed.
        existingTokenURL=$(git config --global --get-regexp url.*@github.com/.insteadOf)
        echo "All Token:${existingTokenURL}"
        for item in $(echo ${existingTokenURL}); do
          if [ ${item} == "https://github.com/" ]; then
            continue
          fi
          echo "Removing: ${item}"
          git config --global --unset-all "${item}"
        done

    - name: Get Access Token
      id: get_access_token
      uses: adi-innersource/generate-github-app-token-action@v1
      env:
        GH_APP_PEM: ${{ secrets.GH_APP_PEM }}
        GH_APP_ID: ${{ vars.GH_APP_ID }}
        GH_APP_INSTALLATION_ID: ${{ vars.GH_APP_INSTALLATION_ID }}

    - name: Install Python dependencies
      run: |
        sudo pip3 install -U setuptools wheel pip
        pip3 install -U PyGithub>=1.55 west

    - name: Check out source code
      uses: actions/checkout@v4

    - name: Run assignment script
      env:
        GITHUB_TOKEN: ${{ env.generatedAccessToken }}
      run: |
        FLAGS="-v"
        FLAGS+=" -o ${{ github.event.repository.owner.login }}"
        FLAGS+=" -r ${{ github.event.repository.name }}"
        FLAGS+=" -M MAINTAINERS.yml"
        if [ "${{ github.event_name }}" = "pull_request_target" ]; then
            FLAGS+=" -P ${{ github.event.pull_request.number }}"
        elif [ "${{ github.event_name }}" = "issues" ]; then
            FLAGS+=" -I ${{ github.event.issue.number }}"
        elif [ "${{ github.event_name }}" = "schedule" ]; then
            FLAGS+=" --modules"
        else
          echo "Unknown event: ${{ github.event_name }}"
          exit 1
        fi

        python3 scripts/set_assignees.py $FLAGS
